import Movie from '#models/movie'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class MovieSeeder extends BaseSeeder {
  public async run() {
    const movies = [
      { name: 'Le Roi Lion', emojis: '🦁👑🌅🐾🌟' },
      { name: 'Titanic', emojis: '🚢💔🌊❄️🎻' },
      { name: 'Star Wars', emojis: '🌌⚔️🚀🛸👽' },
      { name: 'Jurassic Park', emojis: '🦖🦕🌴⚠️🔬' },
      { name: 'La Reine des Neiges', emojis: '❄️⛄👸🌨️🎵' },
      { name: 'Le Monde de Nemo', emojis: '🐟🔍🌊🐢🦈' },
      { name: 'Matrix', emojis: '💻🕶️🔫🧑‍💻📉' },
      { name: 'Harry Potter', emojis: '🪄⚡🎓🧙‍♂️🐉' },
      { name: 'Avengers', emojis: '🛡️💥🌍🦸‍♂️🦸‍♀️' },
      { name: 'Coco', emojis: '🎸💀🌼👨‍👩‍👧‍👦🇲🇽' },
      { name: 'Avatar', emojis: '🌀🧝🌌🌿🐉' },
      { name: 'Shrek', emojis: '🟢👑🐉👰🤣' },
      { name: 'Toy Story', emojis: '🤠🧸🚀👨‍🚀✨' },
      { name: 'Les Minions', emojis: '🍌😂😎🔧💛' },
      { name: 'La Belle et la Bête', emojis: '🌹👸🐻🏰🎵' },
      { name: 'Aladdin', emojis: '🧞‍♂️🪔🕌🐒✨' },
      { name: 'Spider-Man', emojis: '🕷️🕸️🦸‍♂️🏙️⚡' },
      { name: 'Iron Man', emojis: '🤖🦾🔥🛠️💼' },
      { name: 'La La Land', emojis: '🎶💃🌆🎷✨' },
      { name: 'Pirates des Caraïbes', emojis: '🏴‍☠️⚓🏝️🗺️⚔️' },
      { name: 'Les Indestructibles', emojis: '🦸‍♂️🦸‍♀️👨‍👩‍👧‍👦💪🔥' },
      { name: 'Mulan', emojis: '⚔️👩‍🎤🐉🇨🇳🎵' },
      { name: 'Ratatouille', emojis: '🐀🍝👨‍🍳🗼🎨' },
      { name: 'Le Fabuleux Destin d’Amélie Poulain', emojis: '🎡🍷🎨🌷🇫🇷' },
      { name: 'Là-haut', emojis: '🎈🏠👴🦴🐾' },
      { name: 'Les Évadés', emojis: '⛓️🏃‍♂️🌄🏢' },
      { name: 'Inception', emojis: '💤🌀🏢🕰️🛌' },
      { name: 'Le Seigneur des Anneaux', emojis: '💍🧙‍♂️🗡️🌋👣' },
      { name: 'Forrest Gump', emojis: '🏃‍♂️🍫🪑🎩🇺🇸' },
      { name: 'Les Gardiens de la Galaxie', emojis: '🚀🦝🌌🎵🧑‍🎤' },
      { name: 'Black Panther', emojis: '🖤🐾👑🌍⚡' },
      { name: 'La Vie est Belle', emojis: '🎩💔🇮🇹🎥🏠' },
      { name: 'Gladiator', emojis: '⚔️🛡️🏟️👑🏛️' },
      { name: 'Le Livre de la Jungle', emojis: '🐅🐻🌿👦🔥' },
      { name: 'Les 101 Dalmatiens', emojis: '🐶🐾🎨👩‍🎨🚗' },
      { name: 'Le Voyage de Chihiro', emojis: '🚂👧🎭🐉🎋' },
      { name: 'Intouchables', emojis: '🪑👨‍🦽😂🎵🤝' },
      { name: 'Les Choristes', emojis: '🎶👨‍🏫👦🎵🇫🇷' },
      { name: 'La Petite Sirène', emojis: '🧜‍♀️🌊🎤🐠🐙' },
      { name: 'Mon Voisin Totoro', emojis: '🌳🐾🚏🚌🐈' },
      { name: 'Le Cinquième Élément', emojis: '🌌🔶🛸⚔️🎤' },
      { name: 'The Dark Knight', emojis: '🦇🌃🎭💣🚓' },
      { name: 'Kill Bill', emojis: '💛⚔️🩸👊🎵' },
      { name: 'The Social Network', emojis: '📱🌐🧑‍💻💰👨‍🎓' },
      { name: 'Le Grand Bleu', emojis: '🌊🐬💙🏊‍♂️🌞' },
      { name: 'Wall-E', emojis: '🤖🌎🚀❤️📼' },
      { name: 'Le Parrain', emojis: '🤵🖤🔫🍷💵' },
      { name: 'Le Loup de Wall Street', emojis: '🐺💰📈🍾🏢' },
      { name: 'E.T.', emojis: '👽🚲🌕🏠📞' },
      { name: 'Le Labyrinthe de Pan', emojis: '🌲🌀👧🔮🐐' },
      { name: 'Drive', emojis: '🚗🩸🎵💰🎮' },
      { name: 'Le Prestige', emojis: '🎩✨🎭🎥🪄' },
      { name: 'Interstellar', emojis: '🚀🌌🕒🌾🪐' },
      { name: 'Retour vers le Futur', emojis: '⌛🚗⚡🏙️📅' },
      { name: 'Le Pianiste', emojis: '🎹💔🇵🇱🎼📖' },
      { name: 'Deadpool', emojis: '🤪🔫🍕💣💔' },
      { name: 'Les Nouveaux Héros', emojis: '🤖❤️🏙️⚙️👨‍🔬' },
      { name: 'Big Fish', emojis: '🐟🎩🌳💭✨' },
      { name: 'Le Dernier Samouraï', emojis: '🗡️👘🇯🇵🐎🛡️' },
      { name: 'Parasite', emojis: '🏠🍷💸🎭🇰🇷' },
      { name: 'Fight Club', emojis: '🥊🧼🚬💣👨‍💻' },
      { name: 'Zootopie', emojis: '🦊👮‍♀️🐰🏢🔍' },
    ]

    await Movie.createMany(movies)
  }
}
