export const films = [
  { name: "Le Seigneur des Anneaux", emoji: "🧙‍♂️💍🔥" },
  { name: "Les Dents de la Mer", emoji: "🦈🌊" },
  { name: "Titanic", emoji: "🚢❄️💔" },
  { name: "Captain America", emoji: "🦸‍♂️🛡️" },
  { name: "Jurassic Park", emoji: "🦖🌴" },
  { name: "Kung Fu Panda", emoji: "🐼🥋" },
  { name: "Interstellar", emoji: "🚀👨‍🚀🌌" },
  { name: "E.T.", emoji: "👽📞📡" },
  { name: "Harry Potter", emoji: "🧹✨🧙‍♀️" },
  { name: "Le Roi Lion", emoji: "👑🦁🌍" },
  { name: "Pirates des Caraïbes", emoji: "🏴‍☠️⚔️💎" },
  { name: "Shrek", emoji: "👹🐴👰" },
  { name: "Star Wars", emoji: "🌌⚔️🚀" },
  { name: "Wall-E", emoji: "🤖🌍❤️" },
  { name: "Avatar", emoji: "🌌👽🌳" },
  { name: "Le Monde de Nemo", emoji: "🐠🌊🐢" },
  { name: "Toy Story", emoji: "🤠🧸🚀" },
  { name: "La La Land", emoji: "🎹💃🎵" },
  { name: "Spider-Man", emoji: "🕷️🕸️🦸‍♂️" },
  { name: "Inception", emoji: "🌀💤🕰️" },
  { name: "Forrest Gump", emoji: "🏃‍♂️🍫🪑" },
  { name: "Matrix", emoji: "💊🖥️🤖" },
  { name: "Le Fabuleux Destin d’Amélie Poulain", emoji: "☕📸🌸" },
  { name: "Les Avengers", emoji: "🦸‍♂️🦸‍♀️🌍" },
  { name: "Gladiator", emoji: "⚔️🏟️🛡️" },
  { name: "Dune", emoji: "🏜️👑🌌" },
  { name: "Le Grand Bleu", emoji: "🐋🌊💙" },
  { name: "Charlie et la Chocolaterie", emoji: "🍫🏭👦" },
  { name: "Mad Max", emoji: "🚗🔥🌵" },
  { name: "Le Grinch", emoji: "🎄👹🎁" },
  { name: "Le Hobbit", emoji: "🧙‍♂️🗻💍" },
  { name: "La Reine des Neiges", emoji: "❄️👑⛄" },
  { name: "Là-haut", emoji: "🎈🏠👴" },
  { name: "Les Indestructibles", emoji: "🦸‍♂️🦸‍♀️👨‍👩‍👧‍👦" },
  { name: "Le Silence des Agneaux", emoji: "🦋👮‍♀️🍽️" },
  { name: "Black Panther", emoji: "🐾👑⚔️" },
  { name: "Le Labyrinthe", emoji: "🏃‍♂️🌾🧩" },
  { name: "Cendrillon", emoji: "👸🥿🎃" },
  { name: "Les Misérables", emoji: "🇫🇷🏰🎶" },
  { name: "It", emoji: "🤡🎈👦" },
  { name: "Up", emoji: "🎈🏠🐕" },
  { name: "Aladdin", emoji: "🧞‍♂️🪔🏰" },
  { name: "Le Parrain", emoji: "🤵🔫🌹" },
  { name: "Pulp Fiction", emoji: "💼🍔🔫" },
  { name: "L'Étrange Noël de Monsieur Jack", emoji: "🎄🎃💀" },
  { name: "Les Minions", emoji: "🟡👖🍌" },
  { name: "Fast and Furious", emoji: "🚗💨🔥" },
  { name: "Doctor Strange", emoji: "🧙‍♂️🔮✨" },
  { name: "Le Voyage de Chihiro", emoji: "🐉👧🎐" },
  { name: "Les Simpson : Le Film", emoji: "🍩👨‍👩‍👧‍👦💥" },
  { name: "Zootopie", emoji: "🦊👮‍♀️🐰" },
  { name: "Coco", emoji: "💀🎸🌼" },
  { name: "Moi, Moche et Méchant", emoji: "👨‍🦲🟡🎈" },
  { name: "La Petite Sirène", emoji: "🧜‍♀️🐠🌊" },
  { name: "La Belle et la Bête", emoji: "🌹👸🐻" },
  { name: "Le Joker", emoji: "🤡🔫🎭" },
  { name: "Les 101 Dalmatiens", emoji: "🐶🐾💯" },
  { name: "L'Âge de Glace", emoji: "🦣❄️🍑" },
  { name: "Le Cinquième Élément", emoji: "👩‍🦰🛸💎" },
];
